apiVersion: v1
kind: Service
metadata:
  name: momentum-api
  namespace: stocks
spec:
  type: NodePort
  selector:
    app: momentum-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
